/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessHelpRouteImport } from './routes/access-help'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as AdjustmentsRequestIdRouteImport } from './routes/adjustments_.$requestId'
import { Route as AdjustmentsNewRouteImport } from './routes/adjustments_.new'
import { Route as AiChatSessionIdRouteImport } from './routes/ai-chat_.$sessionId'
import { Route as ComplianceAmlRouteImport } from './routes/compliance_.aml'
import { Route as ComplianceFrozenRouteImport } from './routes/compliance_.frozen'
import { Route as ComplianceMonitoringRouteImport } from './routes/compliance_.monitoring'
import { Route as ComplianceQueueRouteImport } from './routes/compliance_.queue'
import { Route as ComplianceReportingRouteImport } from './routes/compliance_.reporting'
import { Route as MarketingAudienceRouteImport } from './routes/marketing_.audience'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing_.campaigns'
import { Route as MarketingDigestRouteImport } from './routes/marketing_.digest'
import { Route as MarketingFeedRouteImport } from './routes/marketing_.feed'
import { Route as MarketingReferralsRouteImport } from './routes/marketing_.referrals'
import { Route as ProductsProductIdRouteImport } from './routes/products_.$productId'
import { Route as ProductsNewRouteImport } from './routes/products_.new'
import { Route as ProductsPublishedRouteImport } from './routes/products_.published'
import { Route as RatesApprovalsRouteImport } from './routes/rates_.approvals'
import { Route as RatesProposeRouteImport } from './routes/rates_.propose'
import { Route as ReconciliationRecordsRouteImport } from './routes/reconciliation_.records'
import { Route as SupportTicketIdRouteImport } from './routes/support_.$ticketId'
import { Route as TeamAdminIdRouteImport } from './routes/team_.$adminId'
import { Route as TeamNewRouteImport } from './routes/team_.new'
import { Route as TeamRolesRouteImport } from './routes/team_.roles'
import { Route as TransactionsTxnIdRouteImport } from './routes/transactions_.$txnId'
import { Route as UsersUserIdRouteImport } from './routes/users_.$userId'
import { Route as UsersDropoffsRouteImport } from './routes/users_.dropoffs'
import { Route as UsersNewRouteImport } from './routes/users_.new'
import { Route as WithdrawalsWithdrawalIdRouteImport } from './routes/withdrawals_.$withdrawalId'
import { Route as ComplianceAmlAlertIdRouteImport } from './routes/compliance_.aml_.$alertId'
import { Route as ComplianceQueueCaseIdRouteImport } from './routes/compliance_.queue_.$caseId'
import { Route as MarketingCampaignsCampaignIdRouteImport } from './routes/marketing_.campaigns_.$campaignId'
import { Route as MarketingCampaignsNewRouteImport } from './routes/marketing_.campaigns_.new'
import { Route as MarketingFeedNewRouteImport } from './routes/marketing_.feed_.new'
import { Route as RatesApprovalsRequestIdRouteImport } from './routes/rates_.approvals_.$requestId'
import { Route as ReconciliationRecordsRecordIdRouteImport } from './routes/reconciliation_.records_.$recordId'
import { Route as UsersUserIdIndexRouteImport } from './routes/users_.$userId.index'
import { Route as UsersUserIdAuditRouteImport } from './routes/users_.$userId.audit'
import { Route as UsersUserIdBalancesRouteImport } from './routes/users_.$userId.balances'
import { Route as UsersUserIdFrozenRouteImport } from './routes/users_.$userId.frozen'
import { Route as UsersUserIdInvestmentsRouteImport } from './routes/users_.$userId.investments'
import { Route as UsersUserIdKycRouteImport } from './routes/users_.$userId.kyc'
import { Route as UsersUserIdSessionsRouteImport } from './routes/users_.$userId.sessions'
import { Route as UsersUserIdSupportRouteImport } from './routes/users_.$userId.support'
import { Route as UsersUserIdTransactionsRouteImport } from './routes/users_.$userId.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessHelpRoute = AccessHelpRouteImport.update({
  id: '/access-help',
  path: '/access-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRequestIdRoute = AdjustmentsRequestIdRouteImport.update({
  id: '/adjustments_/$requestId',
  path: '/adjustments/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsNewRoute = AdjustmentsNewRouteImport.update({
  id: '/adjustments_/new',
  path: '/adjustments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatSessionIdRoute = AiChatSessionIdRouteImport.update({
  id: '/ai-chat_/$sessionId',
  path: '/ai-chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceAmlRoute = ComplianceAmlRouteImport.update({
  id: '/compliance_/aml',
  path: '/compliance/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceFrozenRoute = ComplianceFrozenRouteImport.update({
  id: '/compliance_/frozen',
  path: '/compliance/frozen',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceMonitoringRoute = ComplianceMonitoringRouteImport.update({
  id: '/compliance_/monitoring',
  path: '/compliance/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceQueueRoute = ComplianceQueueRouteImport.update({
  id: '/compliance_/queue',
  path: '/compliance/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceReportingRoute = ComplianceReportingRouteImport.update({
  id: '/compliance_/reporting',
  path: '/compliance/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAudienceRoute = MarketingAudienceRouteImport.update({
  id: '/marketing_/audience',
  path: '/marketing/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/marketing_/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingDigestRoute = MarketingDigestRouteImport.update({
  id: '/marketing_/digest',
  path: '/marketing/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFeedRoute = MarketingFeedRouteImport.update({
  id: '/marketing_/feed',
  path: '/marketing/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingReferralsRoute = MarketingReferralsRouteImport.update({
  id: '/marketing_/referrals',
  path: '/marketing/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPublishedRoute = ProductsPublishedRouteImport.update({
  id: '/products_/published',
  path: '/products/published',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesApprovalsRoute = RatesApprovalsRouteImport.update({
  id: '/rates_/approvals',
  path: '/rates/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesProposeRoute = RatesProposeRouteImport.update({
  id: '/rates_/propose',
  path: '/rates/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRecordsRoute = ReconciliationRecordsRouteImport.update({
  id: '/reconciliation_/records',
  path: '/reconciliation/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/support_/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAdminIdRoute = TeamAdminIdRouteImport.update({
  id: '/team_/$adminId',
  path: '/team/$adminId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team_/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRolesRoute = TeamRolesRouteImport.update({
  id: '/team_/roles',
  path: '/team/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTxnIdRoute = TransactionsTxnIdRouteImport.update({
  id: '/transactions_/$txnId',
  path: '/transactions/$txnId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersDropoffsRoute = UsersDropoffsRouteImport.update({
  id: '/users_/dropoffs',
  path: '/users/dropoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsWithdrawalIdRoute = WithdrawalsWithdrawalIdRouteImport.update({
  id: '/withdrawals_/$withdrawalId',
  path: '/withdrawals/$withdrawalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceAmlAlertIdRoute = ComplianceAmlAlertIdRouteImport.update({
  id: '/compliance_/aml_/$alertId',
  path: '/compliance/aml/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceQueueCaseIdRoute = ComplianceQueueCaseIdRouteImport.update({
  id: '/compliance_/queue_/$caseId',
  path: '/compliance/queue/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsCampaignIdRoute =
  MarketingCampaignsCampaignIdRouteImport.update({
    id: '/marketing_/campaigns_/$campaignId',
    path: '/marketing/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingCampaignsNewRoute = MarketingCampaignsNewRouteImport.update({
  id: '/marketing_/campaigns_/new',
  path: '/marketing/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFeedNewRoute = MarketingFeedNewRouteImport.update({
  id: '/marketing_/feed_/new',
  path: '/marketing/feed/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesApprovalsRequestIdRoute = RatesApprovalsRequestIdRouteImport.update({
  id: '/rates_/approvals_/$requestId',
  path: '/rates/approvals/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRecordsRecordIdRoute =
  ReconciliationRecordsRecordIdRouteImport.update({
    id: '/reconciliation_/records_/$recordId',
    path: '/reconciliation/records/$recordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdAuditRoute = UsersUserIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdBalancesRoute = UsersUserIdBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdFrozenRoute = UsersUserIdFrozenRouteImport.update({
  id: '/frozen',
  path: '/frozen',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdInvestmentsRoute = UsersUserIdInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdKycRoute = UsersUserIdKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdSessionsRoute = UsersUserIdSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdSupportRoute = UsersUserIdSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdTransactionsRoute = UsersUserIdTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => UsersUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-help': typeof AccessHelpRoute
  '/adjustments': typeof AdjustmentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify': typeof VerifyRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/adjustments/$requestId': typeof AdjustmentsRequestIdRoute
  '/adjustments/new': typeof AdjustmentsNewRoute
  '/ai-chat/$sessionId': typeof AiChatSessionIdRoute
  '/compliance/aml': typeof ComplianceAmlRoute
  '/compliance/frozen': typeof ComplianceFrozenRoute
  '/compliance/monitoring': typeof ComplianceMonitoringRoute
  '/compliance/queue': typeof ComplianceQueueRoute
  '/compliance/reporting': typeof ComplianceReportingRoute
  '/marketing/audience': typeof MarketingAudienceRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/digest': typeof MarketingDigestRoute
  '/marketing/feed': typeof MarketingFeedRoute
  '/marketing/referrals': typeof MarketingReferralsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/published': typeof ProductsPublishedRoute
  '/rates/approvals': typeof RatesApprovalsRoute
  '/rates/propose': typeof RatesProposeRoute
  '/reconciliation/records': typeof ReconciliationRecordsRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/team/$adminId': typeof TeamAdminIdRoute
  '/team/new': typeof TeamNewRoute
  '/team/roles': typeof TeamRolesRoute
  '/transactions/$txnId': typeof TransactionsTxnIdRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/dropoffs': typeof UsersDropoffsRoute
  '/users/new': typeof UsersNewRoute
  '/withdrawals/$withdrawalId': typeof WithdrawalsWithdrawalIdRoute
  '/compliance/aml/$alertId': typeof ComplianceAmlAlertIdRoute
  '/compliance/queue/$caseId': typeof ComplianceQueueCaseIdRoute
  '/marketing/campaigns/$campaignId': typeof MarketingCampaignsCampaignIdRoute
  '/marketing/campaigns/new': typeof MarketingCampaignsNewRoute
  '/marketing/feed/new': typeof MarketingFeedNewRoute
  '/rates/approvals/$requestId': typeof RatesApprovalsRequestIdRoute
  '/reconciliation/records/$recordId': typeof ReconciliationRecordsRecordIdRoute
  '/users/$userId/audit': typeof UsersUserIdAuditRoute
  '/users/$userId/balances': typeof UsersUserIdBalancesRoute
  '/users/$userId/frozen': typeof UsersUserIdFrozenRoute
  '/users/$userId/investments': typeof UsersUserIdInvestmentsRoute
  '/users/$userId/kyc': typeof UsersUserIdKycRoute
  '/users/$userId/sessions': typeof UsersUserIdSessionsRoute
  '/users/$userId/support': typeof UsersUserIdSupportRoute
  '/users/$userId/transactions': typeof UsersUserIdTransactionsRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-help': typeof AccessHelpRoute
  '/adjustments': typeof AdjustmentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify': typeof VerifyRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/adjustments/$requestId': typeof AdjustmentsRequestIdRoute
  '/adjustments/new': typeof AdjustmentsNewRoute
  '/ai-chat/$sessionId': typeof AiChatSessionIdRoute
  '/compliance/aml': typeof ComplianceAmlRoute
  '/compliance/frozen': typeof ComplianceFrozenRoute
  '/compliance/monitoring': typeof ComplianceMonitoringRoute
  '/compliance/queue': typeof ComplianceQueueRoute
  '/compliance/reporting': typeof ComplianceReportingRoute
  '/marketing/audience': typeof MarketingAudienceRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/digest': typeof MarketingDigestRoute
  '/marketing/feed': typeof MarketingFeedRoute
  '/marketing/referrals': typeof MarketingReferralsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/published': typeof ProductsPublishedRoute
  '/rates/approvals': typeof RatesApprovalsRoute
  '/rates/propose': typeof RatesProposeRoute
  '/reconciliation/records': typeof ReconciliationRecordsRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/team/$adminId': typeof TeamAdminIdRoute
  '/team/new': typeof TeamNewRoute
  '/team/roles': typeof TeamRolesRoute
  '/transactions/$txnId': typeof TransactionsTxnIdRoute
  '/users/dropoffs': typeof UsersDropoffsRoute
  '/users/new': typeof UsersNewRoute
  '/withdrawals/$withdrawalId': typeof WithdrawalsWithdrawalIdRoute
  '/compliance/aml/$alertId': typeof ComplianceAmlAlertIdRoute
  '/compliance/queue/$caseId': typeof ComplianceQueueCaseIdRoute
  '/marketing/campaigns/$campaignId': typeof MarketingCampaignsCampaignIdRoute
  '/marketing/campaigns/new': typeof MarketingCampaignsNewRoute
  '/marketing/feed/new': typeof MarketingFeedNewRoute
  '/rates/approvals/$requestId': typeof RatesApprovalsRequestIdRoute
  '/reconciliation/records/$recordId': typeof ReconciliationRecordsRecordIdRoute
  '/users/$userId/audit': typeof UsersUserIdAuditRoute
  '/users/$userId/balances': typeof UsersUserIdBalancesRoute
  '/users/$userId/frozen': typeof UsersUserIdFrozenRoute
  '/users/$userId/investments': typeof UsersUserIdInvestmentsRoute
  '/users/$userId/kyc': typeof UsersUserIdKycRoute
  '/users/$userId/sessions': typeof UsersUserIdSessionsRoute
  '/users/$userId/support': typeof UsersUserIdSupportRoute
  '/users/$userId/transactions': typeof UsersUserIdTransactionsRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-help': typeof AccessHelpRoute
  '/adjustments': typeof AdjustmentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify': typeof VerifyRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/adjustments_/$requestId': typeof AdjustmentsRequestIdRoute
  '/adjustments_/new': typeof AdjustmentsNewRoute
  '/ai-chat_/$sessionId': typeof AiChatSessionIdRoute
  '/compliance_/aml': typeof ComplianceAmlRoute
  '/compliance_/frozen': typeof ComplianceFrozenRoute
  '/compliance_/monitoring': typeof ComplianceMonitoringRoute
  '/compliance_/queue': typeof ComplianceQueueRoute
  '/compliance_/reporting': typeof ComplianceReportingRoute
  '/marketing_/audience': typeof MarketingAudienceRoute
  '/marketing_/campaigns': typeof MarketingCampaignsRoute
  '/marketing_/digest': typeof MarketingDigestRoute
  '/marketing_/feed': typeof MarketingFeedRoute
  '/marketing_/referrals': typeof MarketingReferralsRoute
  '/products_/$productId': typeof ProductsProductIdRoute
  '/products_/new': typeof ProductsNewRoute
  '/products_/published': typeof ProductsPublishedRoute
  '/rates_/approvals': typeof RatesApprovalsRoute
  '/rates_/propose': typeof RatesProposeRoute
  '/reconciliation_/records': typeof ReconciliationRecordsRoute
  '/support_/$ticketId': typeof SupportTicketIdRoute
  '/team_/$adminId': typeof TeamAdminIdRoute
  '/team_/new': typeof TeamNewRoute
  '/team_/roles': typeof TeamRolesRoute
  '/transactions_/$txnId': typeof TransactionsTxnIdRoute
  '/users_/$userId': typeof UsersUserIdRouteWithChildren
  '/users_/dropoffs': typeof UsersDropoffsRoute
  '/users_/new': typeof UsersNewRoute
  '/withdrawals_/$withdrawalId': typeof WithdrawalsWithdrawalIdRoute
  '/compliance_/aml_/$alertId': typeof ComplianceAmlAlertIdRoute
  '/compliance_/queue_/$caseId': typeof ComplianceQueueCaseIdRoute
  '/marketing_/campaigns_/$campaignId': typeof MarketingCampaignsCampaignIdRoute
  '/marketing_/campaigns_/new': typeof MarketingCampaignsNewRoute
  '/marketing_/feed_/new': typeof MarketingFeedNewRoute
  '/rates_/approvals_/$requestId': typeof RatesApprovalsRequestIdRoute
  '/reconciliation_/records_/$recordId': typeof ReconciliationRecordsRecordIdRoute
  '/users_/$userId/audit': typeof UsersUserIdAuditRoute
  '/users_/$userId/balances': typeof UsersUserIdBalancesRoute
  '/users_/$userId/frozen': typeof UsersUserIdFrozenRoute
  '/users_/$userId/investments': typeof UsersUserIdInvestmentsRoute
  '/users_/$userId/kyc': typeof UsersUserIdKycRoute
  '/users_/$userId/sessions': typeof UsersUserIdSessionsRoute
  '/users_/$userId/support': typeof UsersUserIdSupportRoute
  '/users_/$userId/transactions': typeof UsersUserIdTransactionsRoute
  '/users_/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-help'
    | '/adjustments'
    | '/ai-chat'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/locked'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/rates'
    | '/reconciliation'
    | '/reports'
    | '/search'
    | '/settings'
    | '/support'
    | '/team'
    | '/transactions'
    | '/users'
    | '/verify'
    | '/withdrawals'
    | '/adjustments/$requestId'
    | '/adjustments/new'
    | '/ai-chat/$sessionId'
    | '/compliance/aml'
    | '/compliance/frozen'
    | '/compliance/monitoring'
    | '/compliance/queue'
    | '/compliance/reporting'
    | '/marketing/audience'
    | '/marketing/campaigns'
    | '/marketing/digest'
    | '/marketing/feed'
    | '/marketing/referrals'
    | '/products/$productId'
    | '/products/new'
    | '/products/published'
    | '/rates/approvals'
    | '/rates/propose'
    | '/reconciliation/records'
    | '/support/$ticketId'
    | '/team/$adminId'
    | '/team/new'
    | '/team/roles'
    | '/transactions/$txnId'
    | '/users/$userId'
    | '/users/dropoffs'
    | '/users/new'
    | '/withdrawals/$withdrawalId'
    | '/compliance/aml/$alertId'
    | '/compliance/queue/$caseId'
    | '/marketing/campaigns/$campaignId'
    | '/marketing/campaigns/new'
    | '/marketing/feed/new'
    | '/rates/approvals/$requestId'
    | '/reconciliation/records/$recordId'
    | '/users/$userId/audit'
    | '/users/$userId/balances'
    | '/users/$userId/frozen'
    | '/users/$userId/investments'
    | '/users/$userId/kyc'
    | '/users/$userId/sessions'
    | '/users/$userId/support'
    | '/users/$userId/transactions'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-help'
    | '/adjustments'
    | '/ai-chat'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/locked'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/rates'
    | '/reconciliation'
    | '/reports'
    | '/search'
    | '/settings'
    | '/support'
    | '/team'
    | '/transactions'
    | '/users'
    | '/verify'
    | '/withdrawals'
    | '/adjustments/$requestId'
    | '/adjustments/new'
    | '/ai-chat/$sessionId'
    | '/compliance/aml'
    | '/compliance/frozen'
    | '/compliance/monitoring'
    | '/compliance/queue'
    | '/compliance/reporting'
    | '/marketing/audience'
    | '/marketing/campaigns'
    | '/marketing/digest'
    | '/marketing/feed'
    | '/marketing/referrals'
    | '/products/$productId'
    | '/products/new'
    | '/products/published'
    | '/rates/approvals'
    | '/rates/propose'
    | '/reconciliation/records'
    | '/support/$ticketId'
    | '/team/$adminId'
    | '/team/new'
    | '/team/roles'
    | '/transactions/$txnId'
    | '/users/dropoffs'
    | '/users/new'
    | '/withdrawals/$withdrawalId'
    | '/compliance/aml/$alertId'
    | '/compliance/queue/$caseId'
    | '/marketing/campaigns/$campaignId'
    | '/marketing/campaigns/new'
    | '/marketing/feed/new'
    | '/rates/approvals/$requestId'
    | '/reconciliation/records/$recordId'
    | '/users/$userId/audit'
    | '/users/$userId/balances'
    | '/users/$userId/frozen'
    | '/users/$userId/investments'
    | '/users/$userId/kyc'
    | '/users/$userId/sessions'
    | '/users/$userId/support'
    | '/users/$userId/transactions'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/access-help'
    | '/adjustments'
    | '/ai-chat'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/locked'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/rates'
    | '/reconciliation'
    | '/reports'
    | '/search'
    | '/settings'
    | '/support'
    | '/team'
    | '/transactions'
    | '/users'
    | '/verify'
    | '/withdrawals'
    | '/adjustments_/$requestId'
    | '/adjustments_/new'
    | '/ai-chat_/$sessionId'
    | '/compliance_/aml'
    | '/compliance_/frozen'
    | '/compliance_/monitoring'
    | '/compliance_/queue'
    | '/compliance_/reporting'
    | '/marketing_/audience'
    | '/marketing_/campaigns'
    | '/marketing_/digest'
    | '/marketing_/feed'
    | '/marketing_/referrals'
    | '/products_/$productId'
    | '/products_/new'
    | '/products_/published'
    | '/rates_/approvals'
    | '/rates_/propose'
    | '/reconciliation_/records'
    | '/support_/$ticketId'
    | '/team_/$adminId'
    | '/team_/new'
    | '/team_/roles'
    | '/transactions_/$txnId'
    | '/users_/$userId'
    | '/users_/dropoffs'
    | '/users_/new'
    | '/withdrawals_/$withdrawalId'
    | '/compliance_/aml_/$alertId'
    | '/compliance_/queue_/$caseId'
    | '/marketing_/campaigns_/$campaignId'
    | '/marketing_/campaigns_/new'
    | '/marketing_/feed_/new'
    | '/rates_/approvals_/$requestId'
    | '/reconciliation_/records_/$recordId'
    | '/users_/$userId/audit'
    | '/users_/$userId/balances'
    | '/users_/$userId/frozen'
    | '/users_/$userId/investments'
    | '/users_/$userId/kyc'
    | '/users_/$userId/sessions'
    | '/users_/$userId/support'
    | '/users_/$userId/transactions'
    | '/users_/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessHelpRoute: typeof AccessHelpRoute
  AdjustmentsRoute: typeof AdjustmentsRoute
  AiChatRoute: typeof AiChatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  NotificationsRoute: typeof NotificationsRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RatesRoute: typeof RatesRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
  VerifyRoute: typeof VerifyRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
  AdjustmentsRequestIdRoute: typeof AdjustmentsRequestIdRoute
  AdjustmentsNewRoute: typeof AdjustmentsNewRoute
  AiChatSessionIdRoute: typeof AiChatSessionIdRoute
  ComplianceAmlRoute: typeof ComplianceAmlRoute
  ComplianceFrozenRoute: typeof ComplianceFrozenRoute
  ComplianceMonitoringRoute: typeof ComplianceMonitoringRoute
  ComplianceQueueRoute: typeof ComplianceQueueRoute
  ComplianceReportingRoute: typeof ComplianceReportingRoute
  MarketingAudienceRoute: typeof MarketingAudienceRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingDigestRoute: typeof MarketingDigestRoute
  MarketingFeedRoute: typeof MarketingFeedRoute
  MarketingReferralsRoute: typeof MarketingReferralsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsPublishedRoute: typeof ProductsPublishedRoute
  RatesApprovalsRoute: typeof RatesApprovalsRoute
  RatesProposeRoute: typeof RatesProposeRoute
  ReconciliationRecordsRoute: typeof ReconciliationRecordsRoute
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  TeamAdminIdRoute: typeof TeamAdminIdRoute
  TeamNewRoute: typeof TeamNewRoute
  TeamRolesRoute: typeof TeamRolesRoute
  TransactionsTxnIdRoute: typeof TransactionsTxnIdRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersDropoffsRoute: typeof UsersDropoffsRoute
  UsersNewRoute: typeof UsersNewRoute
  WithdrawalsWithdrawalIdRoute: typeof WithdrawalsWithdrawalIdRoute
  ComplianceAmlAlertIdRoute: typeof ComplianceAmlAlertIdRoute
  ComplianceQueueCaseIdRoute: typeof ComplianceQueueCaseIdRoute
  MarketingCampaignsCampaignIdRoute: typeof MarketingCampaignsCampaignIdRoute
  MarketingCampaignsNewRoute: typeof MarketingCampaignsNewRoute
  MarketingFeedNewRoute: typeof MarketingFeedNewRoute
  RatesApprovalsRequestIdRoute: typeof RatesApprovalsRequestIdRoute
  ReconciliationRecordsRecordIdRoute: typeof ReconciliationRecordsRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-help': {
      id: '/access-help'
      path: '/access-help'
      fullPath: '/access-help'
      preLoaderRoute: typeof AccessHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments_/$requestId': {
      id: '/adjustments_/$requestId'
      path: '/adjustments/$requestId'
      fullPath: '/adjustments/$requestId'
      preLoaderRoute: typeof AdjustmentsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments_/new': {
      id: '/adjustments_/new'
      path: '/adjustments/new'
      fullPath: '/adjustments/new'
      preLoaderRoute: typeof AdjustmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat_/$sessionId': {
      id: '/ai-chat_/$sessionId'
      path: '/ai-chat/$sessionId'
      fullPath: '/ai-chat/$sessionId'
      preLoaderRoute: typeof AiChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/aml': {
      id: '/compliance_/aml'
      path: '/compliance/aml'
      fullPath: '/compliance/aml'
      preLoaderRoute: typeof ComplianceAmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/frozen': {
      id: '/compliance_/frozen'
      path: '/compliance/frozen'
      fullPath: '/compliance/frozen'
      preLoaderRoute: typeof ComplianceFrozenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/monitoring': {
      id: '/compliance_/monitoring'
      path: '/compliance/monitoring'
      fullPath: '/compliance/monitoring'
      preLoaderRoute: typeof ComplianceMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/queue': {
      id: '/compliance_/queue'
      path: '/compliance/queue'
      fullPath: '/compliance/queue'
      preLoaderRoute: typeof ComplianceQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/reporting': {
      id: '/compliance_/reporting'
      path: '/compliance/reporting'
      fullPath: '/compliance/reporting'
      preLoaderRoute: typeof ComplianceReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/audience': {
      id: '/marketing_/audience'
      path: '/marketing/audience'
      fullPath: '/marketing/audience'
      preLoaderRoute: typeof MarketingAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/campaigns': {
      id: '/marketing_/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/digest': {
      id: '/marketing_/digest'
      path: '/marketing/digest'
      fullPath: '/marketing/digest'
      preLoaderRoute: typeof MarketingDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/feed': {
      id: '/marketing_/feed'
      path: '/marketing/feed'
      fullPath: '/marketing/feed'
      preLoaderRoute: typeof MarketingFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/referrals': {
      id: '/marketing_/referrals'
      path: '/marketing/referrals'
      fullPath: '/marketing/referrals'
      preLoaderRoute: typeof MarketingReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$productId': {
      id: '/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/new': {
      id: '/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/published': {
      id: '/products_/published'
      path: '/products/published'
      fullPath: '/products/published'
      preLoaderRoute: typeof ProductsPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates_/approvals': {
      id: '/rates_/approvals'
      path: '/rates/approvals'
      fullPath: '/rates/approvals'
      preLoaderRoute: typeof RatesApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates_/propose': {
      id: '/rates_/propose'
      path: '/rates/propose'
      fullPath: '/rates/propose'
      preLoaderRoute: typeof RatesProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation_/records': {
      id: '/reconciliation_/records'
      path: '/reconciliation/records'
      fullPath: '/reconciliation/records'
      preLoaderRoute: typeof ReconciliationRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support_/$ticketId': {
      id: '/support_/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team_/$adminId': {
      id: '/team_/$adminId'
      path: '/team/$adminId'
      fullPath: '/team/$adminId'
      preLoaderRoute: typeof TeamAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team_/new': {
      id: '/team_/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team_/roles': {
      id: '/team_/roles'
      path: '/team/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof TeamRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/$txnId': {
      id: '/transactions_/$txnId'
      path: '/transactions/$txnId'
      fullPath: '/transactions/$txnId'
      preLoaderRoute: typeof TransactionsTxnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId': {
      id: '/users_/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/dropoffs': {
      id: '/users_/dropoffs'
      path: '/users/dropoffs'
      fullPath: '/users/dropoffs'
      preLoaderRoute: typeof UsersDropoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/new': {
      id: '/users_/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals_/$withdrawalId': {
      id: '/withdrawals_/$withdrawalId'
      path: '/withdrawals/$withdrawalId'
      fullPath: '/withdrawals/$withdrawalId'
      preLoaderRoute: typeof WithdrawalsWithdrawalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/aml_/$alertId': {
      id: '/compliance_/aml_/$alertId'
      path: '/compliance/aml/$alertId'
      fullPath: '/compliance/aml/$alertId'
      preLoaderRoute: typeof ComplianceAmlAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/queue_/$caseId': {
      id: '/compliance_/queue_/$caseId'
      path: '/compliance/queue/$caseId'
      fullPath: '/compliance/queue/$caseId'
      preLoaderRoute: typeof ComplianceQueueCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/campaigns_/$campaignId': {
      id: '/marketing_/campaigns_/$campaignId'
      path: '/marketing/campaigns/$campaignId'
      fullPath: '/marketing/campaigns/$campaignId'
      preLoaderRoute: typeof MarketingCampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/campaigns_/new': {
      id: '/marketing_/campaigns_/new'
      path: '/marketing/campaigns/new'
      fullPath: '/marketing/campaigns/new'
      preLoaderRoute: typeof MarketingCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing_/feed_/new': {
      id: '/marketing_/feed_/new'
      path: '/marketing/feed/new'
      fullPath: '/marketing/feed/new'
      preLoaderRoute: typeof MarketingFeedNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates_/approvals_/$requestId': {
      id: '/rates_/approvals_/$requestId'
      path: '/rates/approvals/$requestId'
      fullPath: '/rates/approvals/$requestId'
      preLoaderRoute: typeof RatesApprovalsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation_/records_/$recordId': {
      id: '/reconciliation_/records_/$recordId'
      path: '/reconciliation/records/$recordId'
      fullPath: '/reconciliation/records/$recordId'
      preLoaderRoute: typeof ReconciliationRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId/': {
      id: '/users_/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/audit': {
      id: '/users_/$userId/audit'
      path: '/audit'
      fullPath: '/users/$userId/audit'
      preLoaderRoute: typeof UsersUserIdAuditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/balances': {
      id: '/users_/$userId/balances'
      path: '/balances'
      fullPath: '/users/$userId/balances'
      preLoaderRoute: typeof UsersUserIdBalancesRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/frozen': {
      id: '/users_/$userId/frozen'
      path: '/frozen'
      fullPath: '/users/$userId/frozen'
      preLoaderRoute: typeof UsersUserIdFrozenRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/investments': {
      id: '/users_/$userId/investments'
      path: '/investments'
      fullPath: '/users/$userId/investments'
      preLoaderRoute: typeof UsersUserIdInvestmentsRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/kyc': {
      id: '/users_/$userId/kyc'
      path: '/kyc'
      fullPath: '/users/$userId/kyc'
      preLoaderRoute: typeof UsersUserIdKycRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/sessions': {
      id: '/users_/$userId/sessions'
      path: '/sessions'
      fullPath: '/users/$userId/sessions'
      preLoaderRoute: typeof UsersUserIdSessionsRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/support': {
      id: '/users_/$userId/support'
      path: '/support'
      fullPath: '/users/$userId/support'
      preLoaderRoute: typeof UsersUserIdSupportRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users_/$userId/transactions': {
      id: '/users_/$userId/transactions'
      path: '/transactions'
      fullPath: '/users/$userId/transactions'
      preLoaderRoute: typeof UsersUserIdTransactionsRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
  }
}

interface UsersUserIdRouteChildren {
  UsersUserIdAuditRoute: typeof UsersUserIdAuditRoute
  UsersUserIdBalancesRoute: typeof UsersUserIdBalancesRoute
  UsersUserIdFrozenRoute: typeof UsersUserIdFrozenRoute
  UsersUserIdInvestmentsRoute: typeof UsersUserIdInvestmentsRoute
  UsersUserIdKycRoute: typeof UsersUserIdKycRoute
  UsersUserIdSessionsRoute: typeof UsersUserIdSessionsRoute
  UsersUserIdSupportRoute: typeof UsersUserIdSupportRoute
  UsersUserIdTransactionsRoute: typeof UsersUserIdTransactionsRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdAuditRoute: UsersUserIdAuditRoute,
  UsersUserIdBalancesRoute: UsersUserIdBalancesRoute,
  UsersUserIdFrozenRoute: UsersUserIdFrozenRoute,
  UsersUserIdInvestmentsRoute: UsersUserIdInvestmentsRoute,
  UsersUserIdKycRoute: UsersUserIdKycRoute,
  UsersUserIdSessionsRoute: UsersUserIdSessionsRoute,
  UsersUserIdSupportRoute: UsersUserIdSupportRoute,
  UsersUserIdTransactionsRoute: UsersUserIdTransactionsRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessHelpRoute: AccessHelpRoute,
  AdjustmentsRoute: AdjustmentsRoute,
  AiChatRoute: AiChatRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  NotificationsRoute: NotificationsRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RatesRoute: RatesRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
  VerifyRoute: VerifyRoute,
  WithdrawalsRoute: WithdrawalsRoute,
  AdjustmentsRequestIdRoute: AdjustmentsRequestIdRoute,
  AdjustmentsNewRoute: AdjustmentsNewRoute,
  AiChatSessionIdRoute: AiChatSessionIdRoute,
  ComplianceAmlRoute: ComplianceAmlRoute,
  ComplianceFrozenRoute: ComplianceFrozenRoute,
  ComplianceMonitoringRoute: ComplianceMonitoringRoute,
  ComplianceQueueRoute: ComplianceQueueRoute,
  ComplianceReportingRoute: ComplianceReportingRoute,
  MarketingAudienceRoute: MarketingAudienceRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingDigestRoute: MarketingDigestRoute,
  MarketingFeedRoute: MarketingFeedRoute,
  MarketingReferralsRoute: MarketingReferralsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsPublishedRoute: ProductsPublishedRoute,
  RatesApprovalsRoute: RatesApprovalsRoute,
  RatesProposeRoute: RatesProposeRoute,
  ReconciliationRecordsRoute: ReconciliationRecordsRoute,
  SupportTicketIdRoute: SupportTicketIdRoute,
  TeamAdminIdRoute: TeamAdminIdRoute,
  TeamNewRoute: TeamNewRoute,
  TeamRolesRoute: TeamRolesRoute,
  TransactionsTxnIdRoute: TransactionsTxnIdRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersDropoffsRoute: UsersDropoffsRoute,
  UsersNewRoute: UsersNewRoute,
  WithdrawalsWithdrawalIdRoute: WithdrawalsWithdrawalIdRoute,
  ComplianceAmlAlertIdRoute: ComplianceAmlAlertIdRoute,
  ComplianceQueueCaseIdRoute: ComplianceQueueCaseIdRoute,
  MarketingCampaignsCampaignIdRoute: MarketingCampaignsCampaignIdRoute,
  MarketingCampaignsNewRoute: MarketingCampaignsNewRoute,
  MarketingFeedNewRoute: MarketingFeedNewRoute,
  RatesApprovalsRequestIdRoute: RatesApprovalsRequestIdRoute,
  ReconciliationRecordsRecordIdRoute: ReconciliationRecordsRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
